const $=id=>document.getElementById(id);let stream=null,recorder=null,chunks=[],recognition=null,running=false,voice=false,recording=false;let words=[],pos=0,manual=0,faceDetector=null,faceReady=false;
const example=`Диагностициран съм с множествена склероза през 2006 година, но първите ми симптоми започнаха още през 2001-ва. Така че реално съм с болестта вече повече от 20 години.

Да, приемам терапия, която е по Здравната каса.

Да. През последните две години имам интензивна кинезитерапия със специалист всяка седмица.

Определено виждам подобрение. Балансът ми е по-добър, походката ми е по-стабилна, а имам и подобрение в силата.

По болнична епикриза имам пареза на крака. При последния профилактичен преглед обаче неврологът я определи като субективна.

Не. Всъщност при мен се е случвало и обратното — имал съм лекари, които са отричали необходимостта от рехабилитация и са ми казвали, че трябва повече да лежа и да почивам.`;
function norm(s){return s.toLowerCase().replace(/[„“"«».,!?;:()[\]{}—–-]/g,' ').replace(/\s+/g,' ').trim()}
function rebuild(){words=norm($('script').value).split(' ').filter(Boolean);$('count').textContent=words.length+' думи';pos=0;manual=0;$('cueText').textContent=$('script').value||'Постави сценария';render()}
function render(){let fs=+$('font').value;$('cueText').style.fontSize=fs+'px';$('cueText').style.opacity=(+$('opacity').value/100);let step=fs*1.18*2.0;$('cueText').style.transform=`translateY(-${Math.max(0,pos+manual)*step/2}px)`}
function speechState(t,ok){$('speechState').textContent=t;$('speechState').style.color=ok?'#86efac':'#fbbf24'}
$('script').oninput=rebuild;$('example').onclick=()=>{$('script').value=example;rebuild()};$('clear').onclick=()=>{$('script').value='';rebuild()};$('font').oninput=()=>{$('fontO').textContent=$('font').value+'px';render()};$('opacity').oninput=()=>{$('opacityO').textContent=$('opacity').value+'%';render()};$('theme').onclick=()=>document.body.classList.toggle('light');
async function cameraStart(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1920},height:{ideal:1080}},audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});$('video').srcObject=stream;$('record').disabled=false;$('start').disabled=false;$('camera').textContent='✅ Камерата е готова';startFace()}catch(e){alert('Не може да се получи достъп до камерата/микрофона: '+e.message)}}$('camera').onclick=cameraStart;
function initSpeech(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){speechState('браузърът не предоставя Speech Recognition',false);$('voice').disabled=true;return}recognition=new SR();recognition.lang='bg-BG';recognition.continuous=true;recognition.interimResults=true;recognition.maxAlternatives=5;recognition.onstart=()=>speechState('активно • bg-BG',true);recognition.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){let t=e.results[i][0].transcript;if(e.results[i].isFinal)lastFinal+=' '+t;else interim+=' '+t}let h=norm(lastFinal+' '+interim);$('heard').textContent=h||'—';if(running)matchScript(h)};recognition.onerror=e=>{speechState('грешка: '+e.error,false);if(e.error==='not-allowed'||e.error==='service-not-allowed'){voice=false;$('voice').textContent='🎙️ БГ ГЛАС: НЯМА ДОСТЪП'}};recognition.onend=()=>{if(running&&voice)setTimeout(()=>{try{recognition.start()}catch(e){}},250)}}let lastFinal='';
function matchScript(heard){if(!words.length)return;let h=heard.split(' ').filter(Boolean),cur=Math.max(0,pos-3),end=Math.min(words.length,pos+55),best=0,bestI=-1;for(let i=cur;i<end;i++)for(let n=2;n<=6;n++){let score=0;for(let j=0;j<n;j++)if(i+j<words.length&&h.length-n+j>=0&&h[h.length-n+j]===words[i+j])score++;if(score>=2&&score>best){best=score;bestI=i+n}}if(bestI>=pos){pos=Math.min(words.length-1,bestI+1);manual=0;render()}}
$('voice').onclick=()=>{if(!recognition){initSpeech();if(!recognition)return}voice=!voice;$('voice').textContent='🎙️ БГ ГЛАС: '+(voice?'ВКЛ.':'ИЗКЛ.');lastFinal='';if(voice)try{recognition.start()}catch(e){}else try{recognition.stop()}catch(e){}};
$('start').onclick=()=>{if(!words.length)return alert('Постави сценарий.');running=true;$('start').disabled=true;$('pause').disabled=false;if(voice)try{recognition.start()}catch(e){}};$('pause').onclick=()=>{running=false;$('start').disabled=false;$('pause').disabled=true};$('reset').onclick=()=>{pos=0;manual=0;running=false;$('start').disabled=!stream;$('pause').disabled=true;render()};$('up').onclick=()=>{manual-=3;render()};$('down').onclick=()=>{manual+=3;render()};
async function startFace(){if(!window.FaceDetection){$('faceStatus').textContent='Лице: API не зареден';return}try{faceDetector=new FaceDetection({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/face_detection/${f}`});faceDetector.setOptions({model:'short',minDetectionConfidence:.55});faceDetector.onResults(r=>{let c=$('faceCanvas'),v=$('video'),ctx=c.getContext('2d');c.width=v.videoWidth||640;c.height=v.videoHeight||480;ctx.clearRect(0,0,c.width,c.height);let fs=r.detections||[];$('faceStatus').textContent='Лице: '+(fs.length?fs.length+' открито':'не е открито');ctx.strokeStyle='#22c55e';ctx.lineWidth=Math.max(3,c.width/220);fs.forEach(d=>{let b=d.boundingBox;ctx.strokeRect(b.xCenter*c.width-b.width*c.width/2,b.yCenter*c.height-b.height*c.height/2,b.width*c.width,b.height*c.height)})});faceReady=true;faceLoop()}catch(e){$('faceStatus').textContent='Лице: грешка'}}
async function faceLoop(){if(faceReady&&stream&&$('video').readyState>=2)try{await faceDetector.send({image:$('video')})}catch(e){}requestAnimationFrame(faceLoop)}
$('record').onclick=()=>{if(!stream)return;if(!recorder||recorder.state==='inactive'){chunks=[];let mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9,opus')?'video/webm;codecs=vp9,opus':'video/webm';recorder=new MediaRecorder(stream,{mimeType:mime});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{let url=URL.createObjectURL(new Blob(chunks,{type:recorder.mimeType}));$('download').href=url;$('download').download='bg-autocue-video.webm';$('download').classList.remove('hidden')};recorder.start();$('cameraWrap').classList.add('recording');$('record').textContent='⏹ Спри'}else{recorder.stop();$('cameraWrap').classList.remove('recording');$('record').textContent='⏺ Запис'}};initSpeech();rebuild();